// AUTO-GENERATED by ffs-sdk (FUT-228) — DO NOT EDIT BY HAND.
//
//   regenerate:  cd ~/Downloads/g2cfw/g2flash && ./tools/ffs-sdk gen
//   source of truth:  g2flash/payloads/manifest.json  (+ the .c files it names)
//
// Each `b64` below is base64("FXP1" + blob), i.e. the FXP1 magic is ALREADY
// included. Do not prepend it again: patches/loader.c:96 rejects a frame without
// the magic and G2Central.swift:806-809 refuses to add a second one, so a
// double-framed or unframed payload pushes "successfully", runs nothing, and
// returns no ret= — which looks exactly like a failed experiment.
//
// The FUT238 STYLE PROBE payload is deliberately NOT here. It is published and
// load-bearing, so it stays a hand-written literal in App.tsx.

import { theme } from "./theme";

export type GeneratedPayload = {
  /** stable id, matches payloads/manifest.json */
  id: string;
  /** the constant name this replaced in App.tsx, kept so old notes still resolve */
  legacyConst: string;
  /** payloads/<source> in the g2flash CFW repo */
  source: string;
  /** exact -D flags handed to patches/build.py */
  defines: string[];
  /** base64("FXP1" + blob) — magic INCLUDED */
  b64: string;
  /** length of the framed payload in bytes (magic + blob), cap 8192 */
  framedBytes: number;
  badge: string;
  tint: string;
  title: string;
  subtitle?: string;
  tag?: string;
  tagTint?: string;
  trace?: string;
  divider?: boolean;
  /** telemetry key passed to guardedPush */
  pushKey: string;
  /** human label passed to guardedPush */
  pushLabel: string;
};

export const GENERATED_PAYLOADS: GeneratedPayload[] = [
  {
    id: "a",
    legacyConst: "PAYLOAD_A_B64",
    source: "payload_a.c",
    defines: [],
    b64:
      "RlhQMS3p8E+DsE/2v0EERsDyRAEAIIhHACgA8MqATfaDYcDyQwGIRwAoAPDGgE/ywUNC9mkKRPbTR0v2GxlP8psIwPJDA0/0lnFYIgVGwPJICsDyRwfA8kQJwPJDCJhHKEaKIWQiwEcgILhHyLMAIQFwQXCBcMFwAXFBcYFxwXEBckFygXLBcgFzQXOBc8FzAXRBdIF0wXQBdUF1gXXBdQF2QXaBdsF2AXdBd4F3wXcdIQAiBkbQRzBGMCEDItBHMEYyIf8i0EcwRjEhb/B/QtBHMEYMIQoi0EcoRjFGACLIR0nyF0vA8kkLKEbYRwAoWtAGRiAgT/AgCbhH2LMHRgAgOHB4cLhw+HA4cXhxuHH4cThyeHK4cvhyOHN4c7hz+HM4dHh0uHT4dDh1eHW4dfh1OHZ4drh2+HY4d3h3uHf4d0Ty3GDC8gcAAmgSsThGWiHQRzhGWCFv8H9C0Ec4Rlkh/yLQR0v2GxMwRjlGACLA8kQDmEdPII34BABUII34BQBBII34BgCN+AeQjfgIAAAgjfgJAAvxGAIBqTBGkEcwRnYhHiLARyVgCiADsL3o8I8BIAOwvejwjwIgA7C96PCP",
    framedBytes: 450,
    badge: "A",
    tint: theme.tint.amber,
    title: "Push payload A",
    subtitle: "Draws a bordered box + label on the HUD. No reflash.",
    tag: "no flash",
    pushKey: "push_a",
    pushLabel: "payload A",
  },
  {
    id: "b",
    legacyConst: "PAYLOAD_B_B64",
    source: "payload_b.c",
    defines: [],
    b64:
      "RlhQMS3p8E+DsE/2v0EERsDyRAEAIIhHACgA8MuATfaDYcDyQwGIRwAoAPDHgE/ywUNC9mkKRPbTR0v2GxlP8psIwPJDA0/0yHGCIgVGwPJICsDyRwfA8kQJwPJDCJhHKEZYIU8iwEcgILhHyLMAIQFwQXCBcMFwAXFBcYFxwXEBckFygXLBcgFzQXOBc8FzAXRBdIF0wXQBdUF1gXXBdQF2QXaBdsF2AXdBd4F3wXcdIQAiBkbQRzBGMCEGItBHMEYyIf8i0EcwRjEhb/B/QtBHMEYMIRoi0EcoRjFGACLIR0nyF0vA8kkLKEbYRwAoW9AGRiAgT/AgCbhH2LMHRgAgOHB4cLhw+HA4cXhxuHH4cThyeHK4cvhyOHN4c7hz+HM4dHh0uHT4dDh1eHW4dfh1OHZ4drh2+HY4d3h3uHf4d0Ty3GDC8gcAAmgSsThGWiHQRzhGWCFv8H9C0Ec4Rlkh/yLQR0v2GxMwRjlGACLA8kQDmEdPII34BABUII34BQBBII34BgBCII34B5CN+AgAACCN+AkAC/EYAgGpMEaQRzBGniEyIsBHJWALIAOwvejwjwEgA7C96PCPAiADsL3o8I8=",
    framedBytes: 452,
    badge: "B",
    tint: theme.tint.green,
    title: "Push payload B",
    subtitle: "Same, different content — pushing B after A visibly replaces it.",
    tag: "no flash",
    divider: true,
    pushKey: "push_b",
    pushLabel: "payload B",
  },
  {
    id: "wa_s17",
    legacyConst: "PAYLOAD_WA_S17_B64",
    source: "payload_widgets_all.c",
    defines: ["-DONLY=17"],
    b64:
      "RlhQMS3p8EOBsE/2v0GARsDyRAEAIIhHACgA8IeARvJceQVGwPJ1CUz2mXbA8kQGSEYpRrBHcLEG9axxB0aIRzxoBvUCYThGiEdMRQPRACTF9gIkAeBP8LRERfIAEMDydQApRrBHAChi0Ab1rHEFRohHT/LBQ8DyQwMoRngheCLI+ABQmEdP8psDwPJDAyhG5CFUIphHRPbTQcDyRwEgIIhHAChE0AAhQvZpBwFwQXCBcMFwAXFBcYFxwXEBckFygXLBcgFzQXOBc8FzAXRBdIF0wXQBdUF1gXXBdQF2QXaBdsF2AXdBd4F3wXfA8kgHHSEAIgZGuEcwRighAyK4RzBGJCH/IrhHMEYjIW/wf0K4RzBGDCE8IrhHS/YbE8DyRAMoRjFGACKYRwHgT/BgRCBGAbC96PCD",
    framedBytes: 312,
    badge: "S17",
    tint: theme.tint.amber,
    title: "Single probe — S17",
    subtitle: "bit 17 ONLY: win — never tested alone, it was hidden inside U16",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_s17",
    pushLabel: "S17",
  },
  {
    id: "wa_s19",
    legacyConst: "PAYLOAD_WA_S19_B64",
    source: "payload_widgets_all.c",
    defines: ["-DONLY=19"],
    b64:
      "RlhQMS3p8EOBsE/2v0GARsDyRAEAIIhHACgA8IWARfIcOQVGwPJ1CUz2mXbA8kQGSEYpRrBHcLEG9axxBEaIRydoBvUCYSBGiEdPRQPRACTF9ggkAeBP8LREqfUHcClGsEcAKGLQBvWscQVGiEdP8sFDwPJDAyhGeCF4Isj4AFCYR0/ymwPA8kMDKEbkIVQimEdE9tNBwPJHASAgiEcAKETQACFC9mkHAXBBcIFwwXABcUFxgXHBcQFyQXKBcsFyAXNBc4FzwXMBdEF0gXTBdAF1QXWBdcF1AXZBdoF2wXYBd0F3gXfBd8DySAcdIQAiBka4RzBGKCEDIrhHMEYkIf8iuEcwRiMhb/B/QrhHMEYMITwiuEdL9hsTwPJEAyhGMUYAIphHAeBP8GBEIEYBsL3o8IM=",
    framedBytes: 308,
    badge: "S19",
    tint: theme.tint.amber,
    title: "Single probe — S19",
    subtitle: "bit 19 ONLY: calendar",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_s19",
    pushLabel: "S19",
  },
  {
    id: "wa_s20",
    legacyConst: "PAYLOAD_WA_S20_B64",
    source: "payload_widgets_all.c",
    defines: ["-DONLY=20"],
    b64:
      "RlhQMS3p8EOBsE/2v0GARsDyRAEAIIhHACgA8IWARfJAOQVGwPJ1CUz2mXbA8kQGSEYpRrBHcLEG9axxBEaIRydoBvUCYSBGiEdPRQPRACTF9hAkAeBP8LREqfUQcClGsEcAKGLQBvWscQVGiEdP8sFDwPJDAyhGeCF4Isj4AFCYR0/ymwPA8kMDKEbkIVQimEdE9tNBwPJHASAgiEcAKETQACFC9mkHAXBBcIFwwXABcUFxgXHBcQFyQXKBcsFyAXNBc4FzwXMBdEF0gXTBdAF1QXWBdcF1AXZBdoF2wXYBd0F3gXfBd8DySAcdIQAiBka4RzBGKCEDIrhHMEYkIf8iuEcwRiMhb/B/QrhHMEYMITwiuEdL9hsTwPJEAyhGMUYAIphHAeBP8GBEIEYBsL3o8IM=",
    framedBytes: 308,
    badge: "S20",
    tint: theme.tint.amber,
    title: "Single probe — S20",
    subtitle: "bit 20 ONLY: calendar_hdr_arrow",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_s20",
    pushLabel: "S20",
  },
  {
    id: "wa_s21",
    legacyConst: "PAYLOAD_WA_S21_B64",
    source: "payload_widgets_all.c",
    defines: ["-DONLY=21"],
    b64:
      "RlhQMS3p8EOBsE/2v0GARsDyRAEAIIhHACgA8IWARfKIOQVGwPJ1CUz2mXbA8kQGSEYpRrBHcLEG9axxBEaIRydoBvUCYSBGiEdPRQPRACTF9iAkAeBP8LREqfUicClGsEcAKGLQBvWscQVGiEdP8sFDwPJDAyhGeCF4Isj4AFCYR0/ymwPA8kMDKEbkIVQimEdE9tNBwPJHASAgiEcAKETQACFC9mkHAXBBcIFwwXABcUFxgXHBcQFyQXKBcsFyAXNBc4FzwXMBdEF0gXTBdAF1QXWBdcF1AXZBdoF2wXYBd0F3gXfBd8DySAcdIQAiBka4RzBGKCEDIrhHMEYkIf8iuEcwRiMhb/B/QrhHMEYMITwiuEdL9hsTwPJEAyhGMUYAIphHAeBP8GBEIEYBsL3o8IM=",
    framedBytes: 308,
    badge: "S21",
    tint: theme.tint.amber,
    title: "Single probe — S21",
    subtitle: "bit 21 ONLY: calendar_hdr_drop",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_s21",
    pushLabel: "S21",
  },
  {
    id: "wa_s13",
    legacyConst: "PAYLOAD_WA_S13_B64",
    source: "payload_widgets_all.c",
    defines: ["-DONLY=13"],
    b64:
      "RlhQMS3p8EOBsE/2v0GARsDyRAEAIIhHACgA8IiARvLcKQVGwPJ1CUz2mXbA8kQGSEYpRrBHeLEG9axxB0aIRzxoBvUCYThGiEdMRQTRQvIABMX2ACQB4E/wtERF8gAQwPJ1AClGsEcAKGLQBvWscQVGiEdP8sFDwPJDAyhGeCF4Isj4AFCYR0/ymwPA8kMDKEbkIVQimEdE9tNBwPJHASAgiEcAKETQACFC9mkHAXBBcIFwwXABcUFxgXHBcQFyQXKBcsFyAXNBc4FzwXMBdEF0gXTBdAF1QXWBdcF1AXZBdoF2wXYBd0F3gXfBd8DySAcdIQAiBka4RzBGKCEDIrhHMEYkIf8iuEcwRiMhb/B/QrhHMEYMITwiuEdL9hsTwPJEAyhGMUYAIphHAeBP8GBEIEYBsL3o8IM=",
    framedBytes: 314,
    badge: "S13",
    tint: theme.tint.amber,
    title: "Single probe — S13",
    subtitle: "bit 13 ONLY: menu_page — the confirmed crasher, isolated to double-check it",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_s13",
    pushLabel: "S13",
  },
  {
    id: "wa_p14",
    legacyConst: "PAYLOAD_WA_P14_B64",
    source: "payload_widgets_all.c",
    defines: ["-DFROM=14", "-DLIMIT=16"],
    b64:
      "RlhQMS3p8E+BsE/2v0GARsDyRAEAIIhHACgA8J2ARvIAOgRGwPJ1Ckz2mXbA8kQGUEYhRrBHaLEG9axxB0aIRz1oBvUCYThGiEdVRQLRT/SASQHgT/AACUbyJDvA8nULWEYhRrBHYLEG9axxBUaIRy9oBvUCYShGiEdfRQi/CfUASar1kFAhRrBHAChf0Ab1rHEERohHT/LBQ8DyQwMgRngheCLI+ABAmEdP8psDwPJDAyBG5CFUIphHRPbTQcDyRwEgIIhHAChB0AAhQvZpBgFwQXCBcMFwAXFBcYFxwXEBckFygXLBcgFzQXOBc8FzAXRBdIF0wXQBdUF1gXXBdQF2QXaBdsF2AXdBd4F3wXfA8kgGHSEAIgVGsEcoRighAyKwRyhGJCH/IrBHKEYjIW/wf0KwRyhGDCE8IrBHS/YbE8DyRAMgRilGACKYRwnxtEABsL3o8I9P8GBAAbC96PCP",
    framedBytes: 354,
    badge: "R14",
    tint: theme.tint.green,
    title: "Range probe — R14",
    subtitle: "bits 14-15 only: menu_cont + menu_section (skips the bad menu_page)",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_p14",
    pushLabel: "R14",
  },
  {
    id: "wa_p16",
    legacyConst: "PAYLOAD_WA_P16_B64",
    source: "payload_widgets_all.c",
    defines: ["-DONLY=16"],
    b64:
      "RlhQMS3p8EOBsE/2v0GARsDyRAEAIIhHACgA8IeARvKoaQVGwPJ1CUz2mXbA8kQGSEYpRrBHcLEG9axxB0aIRzxoBvUCYThGiEdMRQPRACTF9gEkAeBP8LRERfIAEMDydQApRrBHAChi0Ab1rHEFRohHT/LBQ8DyQwMoRngheCLI+ABQmEdP8psDwPJDAyhG5CFUIphHRPbTQcDyRwEgIIhHAChE0AAhQvZpBwFwQXCBcMFwAXFBcYFxwXEBckFygXLBcgFzQXOBc8FzAXRBdIF0wXQBdUF1gXXBdQF2QXaBdsF2AXdBd4F3wXfA8kgHHSEAIgZGuEcwRighAyK4RzBGJCH/IrhHMEYjIW/wf0K4RzBGDCE8IrhHS/YbE8DyRAMoRjFGACKYRwHgT/BgRCBGAbC96PCD",
    framedBytes: 312,
    badge: "R16",
    tint: theme.tint.green,
    title: "Range probe — R16",
    subtitle: "bit 16 only: tabview",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_p16",
    pushLabel: "R16",
  },
  {
    id: "wa_p18",
    legacyConst: "PAYLOAD_WA_P18_B64",
    source: "payload_widgets_all.c",
    defines: ["-DONLY=18"],
    b64:
      "RlhQMS3p8EOBsE/2v0GARsDyRAEAIIhHACgA8IeARvIsGQVGwPJ1CUz2mXbA8kQGSEYpRrBHcLEG9axxB0aIRzxoBvUCYThGiEdMRQPRACTF9gQkAeBP8LRERfIAEMDydQApRrBHAChi0Ab1rHEFRohHT/LBQ8DyQwMoRngheCLI+ABQmEdP8psDwPJDAyhG5CFUIphHRPbTQcDyRwEgIIhHAChE0AAhQvZpBwFwQXCBcMFwAXFBcYFxwXEBckFygXLBcgFzQXOBc8FzAXRBdIF0wXQBdUF1gXXBdQF2QXaBdsF2AXdBd4F3wXfA8kgHHSEAIgZGuEcwRighAyK4RzBGJCH/IrhHMEYjIW/wf0K4RzBGDCE8IrhHS/YbE8DyRAMoRjFGACKYRwHgT/BgRCBGAbC96PCD",
    framedBytes: 312,
    badge: "R18",
    tint: theme.tint.green,
    title: "Range probe — R18",
    subtitle: "bit 18 only: keyboard",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_p18",
    pushLabel: "R18",
  },
  {
    id: "wa_p19",
    legacyConst: "PAYLOAD_WA_P19_B64",
    source: "payload_widgets_all.c",
    defines: ["-DFROM=19"],
    b64:
      "RlhQMS3p8E+BsE/2v0GARsDyRAEAIIhHACgA8K6ARfIcOgVGwPJ1Ckz2mXvA8kQLUEYpRthHaLEL9axxB0aIRzxoC/UCYThGiEdURQLRT/QAKQHgT/AACQrxJAc4RilG2EdgsQv1rHEERohHJmgL9QJhIEaIR75CCL8J9YAZCvFsBzhGKUbYR2CxC/WscQRGiEcmaAv1AmEgRohHvkIIvwn1ABmq9QdwKUbYRwAoX9AL9axxBUaIR0/ywUPA8kMDKEZ4IXgiyPgAUJhHT/KbA8DyQwMoRuQhVCKYR0T200HA8kcBICCIRwAoQdAAIUL2aQYBcEFwgXDBcAFxQXGBccFxAXJBcoFywXIBc0FzgXPBcwF0QXSBdMF0AXVBdYF1wXUBdkF2gXbBdgF3QXeBd8F3wPJIBh0hACIERrBHIEYoIQMisEcgRiQh/yKwRyBGIyFv8H9CsEcgRgwhPCKwR0v2GxPA8kQDKEYhRgAimEcJ8bRAAbC96PCPT/BgQAGwvejwjw==",
    framedBytes: 388,
    badge: "R19",
    tint: theme.tint.green,
    title: "Range probe — R19",
    subtitle: "bits 19-21: calendar x3",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_p19",
    pushLabel: "R19",
  },
  {
    id: "wa_u16",
    legacyConst: "PAYLOAD_WA_U16_B64",
    source: "payload_widgets_all.c",
    defines: ["-DFROM=16"],
    b64:
      "RlhQMS3p8E+BsE/2v0GARsDyRAEAIIhHACgA8OqARvKoZgVGwPJ1Bkz2mXrA8kQKMEYpRtBHaLEK9axxB0aIRzxoCvUCYThGiEe0QgLRT/SAOQHgT/AACbQ2MEYpRtBHYLEK9axxB0aIRzxoCvUCYThGiEe0Qgi/CfUAOUbyLBbA8nUGMEYpRtBHYLEK9axxB0aIRzxoCvUCYThGiEe0Qgi/CfWAKUXyHDvA8nULWEYpRtBHYLEK9axxB0aIRzxoCvUCYThGiEdcRQi/CfUAKQvxJAc4RilG0EdgsQr1rHEERohHJmgK9QJhIEaIR75CCL8J9YAZC/FsBzhGKUbQR2CxCvWscQRGiEcmaAr1AmEgRohHvkIIvwn1ABmr9QdwKUbQRwAoX9AK9axxBUaIR0/ywUPA8kMDKEZ4IXgiyPgAUJhHT/KbA8DyQwMoRuQhVCKYR0T200HA8kcBICCIRwAoQdAAIUL2aQYBcEFwgXDBcAFxQXGBccFxAXJBcoFywXIBc0FzgXPBcwF0QXSBdMF0AXVBdYF1wXUBdkF2gXbBdgF3QXeBd8F3wPJIBh0hACIERrBHIEYoIQMisEcgRiQh/yKwRyBGIyFv8H9CsEcgRgwhPCKwR0v2GxPA8kQDKEYhRgAimEcJ8bRAAbC96PCPT/BgQAGwvejwjw==",
    framedBytes: 508,
    badge: "U16",
    tint: theme.tint.blue,
    title: "Upper range — U16",
    subtitle: "bits 16-21 ONLY: tabview, win, keyboard, calendar x3 — skips the menu family entirely",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_u16",
    pushLabel: "U16",
  },
  {
    id: "wa_u16b",
    legacyConst: "PAYLOAD_WA_U16B_B64",
    source: "payload_widgets_all.c",
    defines: ["-DFROM=16", "-DLIMIT=18"],
    b64:
      "RlhQMS3p8E+BsE/2v0GBRsDyRAEAIIhHACgA8J2ARvKoagRGwPJ1Ckz2mXvA8kQLUEYhRthHaLEL9axxB0aIRz5oC/UCYThGiEdWRQLRT/SAOAHgT/AACArxtAYwRiFG2EdgsQv1rHEHRohHPWgL9QJhOEaIR7VCCL8I9QA4RfIAEMDydQAhRthHAChf0Av1rHEERohHT/LBQ8DyQwMgRngheCLJ+ABAmEdP8psDwPJDAyBG5CFUIphHRPbTQcDyRwEgIIhHAChB0AAhQvZpBgFwQXCBcMFwAXFBcYFxwXEBckFygXLBcgFzQXOBc8FzAXRBdIF0wXQBdUF1gXXBdQF2QXaBdsF2AXdBd4F3wXfA8kgGHSEAIgVGsEcoRighAyKwRyhGJCH/IrBHKEYjIW/wf0KwRyhGDCE8IrBHS/YbE8DyRAMgRilGACKYRwjxtEABsL3o8I9P8GBAAbC96PCP",
    framedBytes: 354,
    badge: "U16b",
    tint: theme.tint.blue,
    title: "Upper range — U16b (bits 16-17)",
    subtitle: "bits 16-17 ONLY: tabview + win (the safer half of the upper group)",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_u16b",
    pushLabel: "U16b",
  },
  {
    id: "wa_13",
    legacyConst: "PAYLOAD_WA_13_B64",
    source: "payload_widgets_all.c",
    defines: ["-DLIMIT=13"],
    b64:
      "RlhQMS3p8E+BsE/2v0GBRsDyRAEAIIhHACgA8JGBRfIAGgVGwPJ1Ckz2mXjA8kQIUEYpRsBHaLEI9axxBEaIRyZoCPUCYSBGiEdWRQLRT/ABCwHgT/AAC0byBCDA8nUAAPVzdCBGKUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwvxAgtG8hhgwPJ1AADxSAYwRilGwEd4sQj1rHEHRohHTEbX+ACQCPUCYThGiEexRaFGCL8L8QQLCvU0djBGKUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwvxCAsK9YdWMEYpRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/EQC0byBCbA8nUGMEYpRsBHgLEI9axxBkaIRzRoCPUCYTBGRvIEJsDydQaIR7RCCL8L8SALBvVqdjBGKUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwvxQAtG8hhgwPJ1AClGwEeAsQj1rHEGRohHNGgI9QJhMEaIR0byGGDA8nUAhEIIvwvxgAtG8gQgwPJ1AAD1fHYwRilGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L9YB7RvIYYMDydQAA8WwGMEYpRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/UAe0byGGDA8nUAAPHYBCBGKUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwv1gGsK9St0IEYpRsBHYLEI9axxBkaIRzdoCPUCYTBGiEenQgi/C/UAa0byBCDA8nUAAPG0BCBGKUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwv1gFtQRilGwEcAKF/QCPWscQRGiEdP8sFDwPJDAyBGeCF4Isn4AECYR0/ymwPA8kMDIEbkIVQimEdE9tNBwPJHASAgiEcAKEHQACFC9mkGAXBBcIFwwXABcUFxgXHBcQFyQXKBcsFyAXNBc4FzwXMBdEF0gXTBdAF1QXWBdcF1AXZBdoF2wXYBd0F3gXfBd8DySAYdIQAiBUawRyhGKCEDIrBHKEYkIf8isEcoRiMhb/B/QrBHKEYMITwisEdL9hsTwPJEAyBGKUYAIphHC/G0QAGwvejwj0/wYEABsL3o8I8=",
    framedBytes: 842,
    badge: "M13",
    tint: theme.tint.amber,
    title: "Menu bisect — M13",
    subtitle: "+ lv_menu (bit 12) — the first child-building constructor",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_13",
    pushLabel: "M13",
  },
  {
    id: "wa_14",
    legacyConst: "PAYLOAD_WA_14_B64",
    source: "payload_widgets_all.c",
    defines: ["-DLIMIT=14"],
    b64:
      "RlhQMS3p8E+BsE/2v0GBRsDyRAEAIIhHACgA8KiBRfIAGgVGwPJ1Ckz2mXjA8kQIUEYpRsBHaLEI9axxBEaIRyZoCPUCYSBGiEdWRQLRT/ABCwHgT/AAC0byBCDA8nUAAPVzdCBGKUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwvxAgtG8hhgwPJ1AADxSAYwRilGwEd4sQj1rHEHRohHTEbX+ACQCPUCYThGiEexRaFGCL8L8QQLCvU0djBGKUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwvxCAsK9YdWMEYpRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/EQC0byBCbA8nUGMEYpRsBHgLEI9axxBkaIRzRoCPUCYTBGRvIEJsDydQaIR7RCCL8L8SALBvVqdjBGKUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwvxQAtG8hhgwPJ1AClGwEeAsQj1rHEGRohHNGgI9QJhMEaIR0byGGDA8nUAhEIIvwvxgAtG8gQgwPJ1AAD1fHYwRilGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L9YB7RvIYYMDydQAA8WwGMEYpRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/UAe0byGGDA8nUAAPHYBCBGKUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwv1gGsK9St0IEYpRsBHYLEI9axxBkaIRzdoCPUCYTBGiEenQgi/C/UAa0byBCbA8nUGBvG0BCBGKUbAR4CxCPWscQZGiEc3aAj1AmEwRkbyBCbA8nUGiEenQgi/C/WAWwbx2AQgRilGwEdgsQj1rHEGRohHN2gI9QJhMEaIR6dCCL8L9QBbUEYpRsBHAChf0Aj1rHEERohHT/LBQ8DyQwMgRngheCLJ+ABAmEdP8psDwPJDAyBG5CFUIphHRPbTQcDyRwEgIIhHAChB0AAhQvZpBgFwQXCBcMFwAXFBcYFxwXEBckFygXLBcgFzQXOBc8FzAXRBdIF0wXQBdUF1gXXBdQF2QXaBdsF2AXdBd4F3wXfA8kgGHSEAIgVGsEcoRighAyKwRyhGJCH/IrBHKEYjIW/wf0KwRyhGDCE8IrBHS/YbE8DyRAMgRilGACKYRwvxtEABsL3o8I9P8GBAAbC96PCP",
    framedBytes: 888,
    badge: "M14",
    tint: theme.tint.amber,
    title: "Menu bisect — M14",
    subtitle: "+ lv_menu_page (bit 13)",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_14",
    pushLabel: "M14",
  },
  {
    id: "wa_15",
    legacyConst: "PAYLOAD_WA_15_B64",
    source: "payload_widgets_all.c",
    defines: ["-DLIMIT=15"],
    b64:
      "RlhQMS3p8E+BsE/2v0GBRsDyRAEAIIhHACgA8L+BRfIAGgVGwPJ1Ckz2mXjA8kQIUEYpRsBHaLEI9axxBEaIRyZoCPUCYSBGiEdWRQLRT/ABCwHgT/AAC0byBCDA8nUAAPVzdCBGKUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwvxAgtG8hhgwPJ1AADxSAYwRilGwEd4sQj1rHEHRohHTEbX+ACQCPUCYThGiEexRaFGCL8L8QQLCvU0djBGKUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwvxCAsK9YdWMEYpRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/EQC0byBCbA8nUGMEYpRsBHgLEI9axxBkaIRzRoCPUCYTBGRvIEJsDydQaIR7RCCL8L8SALBvVqdjBGKUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwvxQAtG8hhgwPJ1AClGwEeAsQj1rHEGRohHNGgI9QJhMEaIR0byGGDA8nUAhEIIvwvxgAtG8gQgwPJ1AAD1fHYwRilGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L9YB7RvIYYMDydQAA8WwGMEYpRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/UAe0byGGDA8nUAAPHYBCBGKUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwv1gGsK9St0IEYpRsBHYLEI9axxBkaIRzdoCPUCYTBGiEenQgi/C/UAa0byBCbA8nUGBvG0BCBGKUbAR4CxCPWscQZGiEc3aAj1AmEwRkbyBCbA8nUGiEenQgi/C/WAWwbx2AQgRilGwEeAsQj1rHEGRohHN2gI9QJhMEZG8gQmwPJ1BohHp0IIvwv1AFsG8fwEIEYpRsBHYLEI9axxBkaIRzdoCPUCYTBGiEenQgi/C/WAS1BGKUbARwAoX9AI9axxBEaIR0/ywUPA8kMDIEZ4IXgiyfgAQJhHT/KbA8DyQwMgRuQhVCKYR0T200HA8kcBICCIRwAoQdAAIUL2aQYBcEFwgXDBcAFxQXGBccFxAXJBcoFywXIBc0FzgXPBcwF0QXSBdMF0AXVBdYF1wXUBdkF2gXbBdgF3QXeBd8F3wPJIBh0hACIFRrBHKEYoIQMisEcoRiQh/yKwRyhGIyFv8H9CsEcoRgwhPCKwR0v2GxPA8kQDIEYpRgAimEcL8bRAAbC96PCPT/BgQAGwvejwjw==",
    framedBytes: 934,
    badge: "M15",
    tint: theme.tint.amber,
    title: "Menu bisect — M15",
    subtitle: "+ lv_menu_cont (bit 14)",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_15",
    pushLabel: "M15",
  },
  {
    id: "wa_menund",
    legacyConst: "PAYLOAD_WA_MENUND_B64",
    source: "payload_widgets_all.c",
    defines: ["-DONLY=12", "-DNODELETE=1"],
    b64:
      "RlhQMS3p8EFP9r9BgEbA8kQBACCIRwAoAPCGgEbyuCQFRsDydQRM9pl2wPJEBiBGKUawR1ixBvWscQdGiEc4aKBCBNFB8gAExfYAJAHgT/C0REXyABDA8nUAKUawRwAoX9AG9axxBUaIR0/ywUPA8kMDKEZ4IXgiyPgAUJhHT/KbA8DyQwMoRuQhVCKYR0T200HA8kcBICCIRwAoQdAAIUL2aQcBcEFwgXDBcAFxQXGBccFxAXJBcoFywXIBc0FzgXPBcwF0QXSBdMF0AXVBdYF1wXUBdkF2gXbBdgF3QXeBd8F3wPJIBx0hACIGRrhHMEYoIQMiuEcwRiQh/yK4RzBGIyFv8H9CuEcwRgwhPCK4R0v2GxPA8kQDKEYxRgAimEcgRr3o8IFP8GBAvejwgQ==",
    framedBytes: 304,
    badge: "MND",
    tint: theme.tint.amber,
    title: "Menu bisect — MND",
    subtitle: "lv_menu ONLY, and NOT deleted — separates a constructor fault from a destructor fault",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa_menund",
    pushLabel: "MND",
  },
  {
    id: "wa12",
    legacyConst: "PAYLOAD_WA12_B64",
    source: "payload_widgets_all.c",
    defines: ["-DLIMIT=12"],
    b64:
      "RlhQMS3p8E+BsE/2v0EERsDyRAEAIIhHACgA8GWBRfIAGYJGwPJ1CUz2mXjA8kQISEZRRgCUwEdosQj1rHEERohHJmgI9QJhIEaIR05FAtFP8AELAeBP8AALRvIEJcDydQUF9XN3OEZRRsBHYLEI9axxBkaIRzRoCPUCYTBGiEe8Qgi/C/ECC0byGGDA8nUAAPFIBjBGUUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwvxBAsJ9TR2MEZRRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/EICwn1h1YwRlFGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L8RALKEZRRsBHYLEI9axxBkaIRzRoCPUCYTBGiEesQgi/C/EgCwX1anYwRlFGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L8UALRvIYZ8DydQc4RlFGwEdgsQj1rHEGRohHNGgI9QJhMEaIR7xCCL8L8YALBfV8dCBGUUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwv1gHtG8hhlwPJ1BQXxbAQgRlFGwEdgsQj1rHEGRohHN2gI9QJhMEaIR6dCCL8L9QB7BfHYBCBGUUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwv1gGsJ9St0IEZRRsBHYLEI9axxBkaIRzdoCPUCYTBGiEenQgi/C/UAa0hGUUbARwAoX9AI9axxBEaIRwCYT/LBQwRgwPJDAyBGeCF4IphHT/KbA8DyQwMgRuQhVCKYR0T200HA8kcBICCIRwAoQdAAIUL2aQYBcEFwgXDBcAFxQXGBccFxAXJBcoFywXIBc0FzgXPBcwF0QXSBdMF0AXVBdYF1wXUBdkF2gXbBdgF3QXeBd8F3wPJIBh0hACIFRrBHKEYoIQMisEcoRiQh/yKwRyhGIyFv8H9CsEcoRgwhPCKwR0v2GxPA8kQDIEYpRgAimEcL8bRAAbC96PCPT/BgQAGwvejwjw==",
    framedBytes: 754,
    badge: "W12",
    tint: theme.tint.amber,
    title: "Sweep bisect \\u2014 first 12 widgets",
    subtitle: "bits 0-11: arc slider switch checkbox led line scale spinner spinbox table textarea chart",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa12",
    pushLabel: "sweep L12",
  },
  {
    id: "wa16",
    legacyConst: "PAYLOAD_WA16_B64",
    source: "payload_widgets_all.c",
    defines: ["-DLIMIT=16"],
    b64:
      "RlhQMS3p8E+BsE/2v0EERsDyRAEAIIhHACgA8LiBRfIAGgVGwPJ1Ckz2mXjA8kQIUEYpRgCUwEdosQj1rHEERohHJmgI9QJhIEaIR1ZFAtFP8AEJAeBP8AAJRvIEK8DydQsL9XN0IEYpRsBHYLEI9axxBkaIRzdoCPUCYTBGiEenQgi/CfECCUbyGGDA8nUAAPFIBjBGKUbAR2CxCPWscQRGiEcnaAj1AmEgRohHt0IIvwnxBAkK9TR2MEYpRsBHYLEI9axxBEaIRydoCPUCYSBGiEe3Qgi/CfEICQr1h1YwRilGwEdgsQj1rHEERohHJ2gI9QJhIEaIR7dCCL8J8RAJWEYpRsBHYLEI9axxBEaIRyZoCPUCYSBGiEdeRQi/CfEgCQv1anYwRilGwEdgsQj1rHEERohHJ2gI9QJhIEaIR7dCCL8J8UAJRvIYYMDydQApRsBHgLEI9axxBEaIRyZoCPUCYSBGiEdG8hhgwPJ1AIZCCL8J8YAJC/V8djBGKUbAR2CxCPWscQRGiEcnaAj1AmEgRohHt0IIvwn1gHlG8hhgwPJ1AADxbAYwRilGwEdgsQj1rHEERohHJ2gI9QJhIEaIR7dCCL8J9QB5RvIYYMDydQAA8dgEIEYpRsBHYLEI9axxBkaIRzdoCPUCYTBGiEenQgi/CfWAaQr1K3QgRilGwEdgsQj1rHEGRohHN2gI9QJhMEaIR6dCCL8J9QBpC/G0BCBGKUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwn1gFkL8dgEIEYpRsBHYLEI9axxBkaIRzdoCPUCYTBGiEenQgi/CfUAWQvx/AQgRilGwEdgsQj1rHEGRohHN2gI9QJhMEaIR6dCCL8J9YBJC/WQdCBGKUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwn1AElQRilGwEcAKF/QCPWscQRGiEcAmE/ywUMEYMDyQwMgRngheCKYR0/ymwPA8kMDIEbkIVQimEdE9tNBwPJHASAgiEcAKEHQACFC9mkGAXBBcIFwwXABcUFxgXHBcQFyQXKBcsFyAXNBc4FzwXMBdEF0gXTBdAF1QXWBdcF1AXZBdoF2wXYBd0F3gXfBd8DySAYdIQAiBUawRyhGKCEDIrBHKEYkIf8isEcoRiMhb/B/QrBHKEYMITwisEdL9hsTwPJEAyBGKUYAIphHCfG0QAGwvejwj0/wYEABsL3o8I8=",
    framedBytes: 920,
    badge: "W16",
    tint: theme.tint.amber,
    title: "Sweep bisect \\u2014 first 16 widgets",
    subtitle: "+ menu menu_page menu_cont menu_section",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa16",
    pushLabel: "sweep L16",
  },
  {
    id: "wa18",
    legacyConst: "PAYLOAD_WA18_B64",
    source: "payload_widgets_all.c",
    defines: ["-DLIMIT=18"],
    b64:
      "RlhQMS3p8E+BsE/2v0EERsDyRAEAIIhHACgA8OCBRfIAGgVGwPJ1Ckz2mXjA8kQIUEYpRgCUwEdosQj1rHEERohHJmgI9QJhIEaIR1ZFAtFP8AELAeBP8AALRvIEKcDydQkJ9XN3OEYpRsBHYLEI9axxBkaIRzRoCPUCYTBGiEe8Qgi/C/ECC0byGGDA8nUAAPFIBjBGKUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwvxBAsK9TR2MEYpRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/EICwr1h1YwRilGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L8RALSEYpRsBHYLEI9axxBkaIRzRoCPUCYTBGiEdMRQi/C/EgCwn1anYwRilGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L8UALRvIYZ8DydQc4RilGwEdgsQj1rHEGRohHNGgI9QJhMEaIR7xCCL8L8YALCfV8djBGKUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwv1gHtG8hhgwPJ1AADxbAYwRilGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L9QB7RvIYYMDydQAA8dgGMEYpRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/WAawr1K3YwRilGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L9QBrCfG0BjBGKUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwv1gFsJ8dgGMEYpRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/UAWwnx/AYwRilGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L9YBLCfWQdCBGKUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwv1AEvRRkbyGGrA8nUKCvGQBCBGKUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwv1gDsK9aJ0IEYpRsBHYLEI9axxBkaIRzdoCPUCYTBGiEenQgi/C/UAO0hGKUbARwAoX9AI9axxBEaIRwCYT/LBQwRgwPJDAyBGeCF4IphHT/KbA8DyQwMgRuQhVCKYR0T200HA8kcBICCIRwAoQdAAIUL2aQYBcEFwgXDBcAFxQXGBccFxAXJBcoFywXIBc0FzgXPBcwF0QXSBdMF0AXVBdYF1wXUBdkF2gXbBdgF3QXeBd8F3wPJIBh0hACIFRrBHKEYoIQMisEcoRiQh/yKwRyhGIyFv8H9CsEcoRgwhPCKwR0v2GxPA8kQDIEYpRgAimEcL8bRAAbC96PCPT/BgQAGwvejwjw==",
    framedBytes: 1000,
    badge: "W18",
    tint: theme.tint.amber,
    title: "Sweep bisect \\u2014 first 18 widgets",
    subtitle: "+ tabview win",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa18",
    pushLabel: "sweep L18",
  },
  {
    id: "wa20",
    legacyConst: "PAYLOAD_WA20_B64",
    source: "payload_widgets_all.c",
    defines: ["-DLIMIT=20"],
    b64:
      "RlhQMS3p8E+BsE/2v0GBRsDyRAEAIIhHACgA8B6CRfIAFYJGwPJ1BUz2mXjA8kQIKEZRRsBHaLEI9axxBEaIRyZoCPUCYSBGiEeuQgLRT/ABCwHgT/AAC0by0FTA8nUEIEZRRsBHoLEI9axxBEaIRyZoCPUCYSBGiEdG8tBQRvLQVMDydQDA8nUEhkIIvwvxAguQNCBGUUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwvxBAsF9TR0IEZRRsBHYLEI9axxBkaIRzdoCPUCYTBGiEenQgi/C/EIC0byLBXA8nUFBfG0BjBGUUbAR3ixCPWscQdGiEdMRtf4AJAI9QJhOEaIR7FFoUYIvwvxEAsF8dgGMEZRRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/EgCwX1kGYwRlFGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L8UALRvLQUMDydQAA8UgGMEZRRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/GAC0by0FDA8nUAAPEkBjBGUUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwv1gHtG8tBQwPJ1AADxtAYwRlFGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L9QB7RvLQUMDydQAA9ZB2MEZRRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/WAa0XyABDA8nUAAPUrdjBGUUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwv1AGsF9cZ2MEZRRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/WAWwX12HYwRlFGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L9QBbBfXqdjBGUUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwv1gEsF9fx2MEZRRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/UAS0by0FDA8nUAAPHYBjBGUUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwv1gDtG8tBQwPJ1AAD1xnYwRlFGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L9QA7KEZRRsBHYLEI9axxBkaIRzRoCPUCYTBGiEesQgi/C/WAK0XyABXA8nUFBfUHdCBGUUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwv1ACsoRlFGwEcAKF/QCPWscQRGiEdP8sFDwPJDAyBGeCF4Isn4AECYR0/ymwPA8kMDIEbkIVQimEdE9tNBwPJHASAgiEcAKEHQACFC9mkGAXBBcIFwwXABcUFxgXHBcQFyQXKBcsFyAXNBc4FzwXMBdEF0gXTBdAF1QXWBdcF1AXZBdoF2wXYBd0F3gXfBd8DySAYdIQAiBUawRyhGKCEDIrBHKEYkIf8isEcoRiMhb/B/QrBHKEYMITwisEdL9hsTwPJEAyBGKUYAIphHC/G0QAGwvejwj0/wYEABsL3o8I8=",
    framedBytes: 1124,
    badge: "W20",
    tint: theme.tint.amber,
    title: "Sweep bisect \\u2014 first 20 widgets",
    subtitle: "+ keyboard calendar",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_wa20",
    pushLabel: "sweep L20",
  },
  {
    id: "widgets_all",
    legacyConst: "PAYLOAD_WIDGETS_ALL_B64",
    source: "payload_widgets_all.c",
    defines: [],
    b64:
      "RlhQMS3p8E+BsE/2v0GBRsDyRAEAIIhHACgA8ESCRfIAFYJGwPJ1BUz2mXjA8kQIKEZRRsBHaLEI9axxBEaIRyZoCPUCYSBGiEeuQgLRT/ABCwHgT/AAC0by0FTA8nUEIEZRRsBHoLEI9axxBEaIRyZoCPUCYSBGiEdG8tBQRvLQVMDydQDA8nUEhkIIvwvxAguQNCBGUUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwvxBAsF9TR0IEZRRsBHYLEI9axxBkaIRzdoCPUCYTBGiEenQgi/C/EIC0byLBXA8nUFBfG0BjBGUUbAR3ixCPWscQdGiEdMRtf4AJAI9QJhOEaIR7FFoUYIvwvxEAsF8dgGMEZRRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/EgCwX1kGYwRlFGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L8UALRvLQUMDydQAA8UgGMEZRRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/GAC0by0FDA8nUAAPEkBjBGUUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwv1gHtG8tBQwPJ1AADxtAYwRlFGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L9QB7RvLQUMDydQAA9ZB2MEZRRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/WAa0XyABDA8nUAAPUrdjBGUUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwv1AGsF9cZ2MEZRRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/WAWwX12HYwRlFGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L9QBbBfXqdjBGUUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwv1gEsF9fx2MEZRRsBHYLEI9axxB0aIRzxoCPUCYThGiEe0Qgi/C/UAS0by0FDA8nUAAPHYBjBGUUbAR2CxCPWscQdGiEc8aAj1AmE4RohHtEIIvwv1gDtG8tBQwPJ1AAD1xnYwRlFGwEdgsQj1rHEHRohHPGgI9QJhOEaIR7RCCL8L9QA7KEZRRsBHYLEI9axxBkaIRzRoCPUCYTBGiEesQgi/C/WAK0XyABXA8nUFBfUHdCBGUUbAR2CxCPWscQZGiEc3aAj1AmEwRohHp0IIvwv1ACsF9RB0IEZRRsBHYLEI9axxBkaIRzdoCPUCYTBGiEenQgi/C/WAGwX1InQgRlFGwEdgsQj1rHEGRohHN2gI9QJhMEaIR6dCCL8L9QAbKEZRRsBHAChf0Aj1rHEERohHT/LBQ8DyQwMgRngheCLJ+ABAmEdP8psDwPJDAyBG5CFUIphHRPbTQcDyRwEgIIhHAChB0AAhQvZpBgFwQXCBcMFwAXFBcYFxwXEBckFygXLBcgFzQXOBc8FzAXRBdIF0wXQBdUF1gXXBdQF2QXaBdsF2AXdBd4F3wXfA8kgGHSEAIgVGsEcoRighAyKwRyhGJCH/IrBHKEYjIW/wf0KwRyhGDCE8IrBHS/YbE8DyRAMgRilGACKYRwvxtEABsL3o8I9P8GBAAbC96PCP",
    framedBytes: 1200,
    badge: "W22",
    tint: theme.tint.green,
    title: "Widget sweep \\u2014 all 22 orphan classes (FUT-232)",
    subtitle: "Creates + verifies + deletes every widget Even never builds. ret=0x5A?????? is a bitmask; bit0 (arc) is the control.",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_widgets_all",
    pushLabel: "widget sweep",
  },
  {
    id: "widget",
    legacyConst: "PAYLOAD_WIDGET_B64",
    source: "payload_widget.c",
    defines: [],
    b64:
      "RlhQMfC1gbBP9r9BBkbA8kQBACCIRwAoctBF8gAUwPJ1BEz2mXcBRsDyRAcgRrhHACho0Af1rHEFRohHT/LBQ8DyQwMoRowhjCI1YJhHT/KbA8DyQwMoRtohSiKYR0T200HA8kcBICCIRwAoQdAAIUL2aQcBcEFwgXDBcAFxQXGBccFxAXJBcoFywXIBc0FzgXPBcwF0QXSBdMF0AXVBdYF1wXUBdkF2gXbBdgF3QXeBd8F3wPJIBx0hACIGRrhHMEYoIQMiuEcwRiQh/yK4RzBGIyFv8H9CuEcwRgwhRiK4R0v2GxPA8kQDKEYxRgAimEcpaOIgoUIIv8cgAbDwveAgAbDwveEgAbDwvQ==",
    framedBytes: 268,
    badge: "W",
    tint: theme.tint.green,
    title: "Widget door \\u2014 build an lv_arc (FUT-232)",
    subtitle: "Constructs a widget Even never builds. ret=0xC7 means it worked; 0xE2 means our class table is wrong.",
    tag: "no flash",
    trace: "FUT-232",
    divider: true,
    pushKey: "push_widget",
    pushLabel: "widget arc",
  },
  {
    id: "an1",
    legacyConst: "PAYLOAD_AN1_B64",
    source: "payload_anim_bisect.c",
    defines: ["-DSTAGE=1"],
    b64:
      "RlhQMS3p8E+DsE/2v0gFRsDyRAgAIMBHACgA8OWATfaDYcDyQwGIRwAoAPDhgE/ywUNC9mkLRPbTSUv2GxdP8psGwPJDA8ghRiIERsDySAvA8kcJwPJEB8DyQwaYRyBGFCFtIrBHICDIR8izACEBcEFwgXDBcAFxQXGBccFxAXJBcoFywXIBc0FzgXPBcwF0QXSBdMF0AXVBdYF1wXUBdkF2gXbBdgF3QXeBd8F3HSEAIgZG2EcwRjAhAyLYRzBGMiH/IthHMEYxIW/wf0LYRzBGDCEKIthHIEYxRgAiuEdJ8hdKwPJJCiBG0EcAKFjQBkYgIMhH2LMHRgAgOHB4cLhw+HA4cXhxuHH4cThyeHK4cvhyOHN4c7hz+HM4dHh0uHT4dDh1eHW4dfh1OHZ4drh2+HY4d3h3uHf4d0Ty3GDC8gcAAmgSsThGWiHYRzhGWCFv8H9C2Ec4Rlkh/yLYR0v2GxMwRjlGACLA8kQDmEdBII34BABOII34BQAxII34BgAAII34BwAK8RgCAakwRpBHT/KbAzBGRiEWIsDyQwOYR2AgLGDIRwVGAChP8AMAF9AI9eNiKEYDJpBHLGBA8i8AwPIAAHhEaGAI9SFjKEYUIU/0snKYR0Dy3FAoY7EgbmQDsL3o8I8BIAOwvejwjwIgA7C96PCPcEc=",
    framedBytes: 506,
    badge: "AN1",
    tint: theme.tint.blue,
    title: "Bisect 1 — box only, animation NOT started",
    subtitle: "Builds the anim struct but never starts it. Should just show a static box labelled AN1.",
    tag: "no flash",
    trace: "FUT-234",
    divider: true,
    pushKey: "push_an1",
    pushLabel: "AN1",
  },
  {
    id: "an2",
    legacyConst: "PAYLOAD_AN2_B64",
    source: "payload_anim_bisect.c",
    defines: ["-DSTAGE=2"],
    b64:
      "RlhQMS3p8E+DsE/2v0gFRsDyRAgAIMBHACgA8O2ATfaDYcDyQwGIRwAoAPDpgE/ywUNC9mkLRPbTSUv2GxdP8psGwPJDA8ghRiIERsDySAvA8kcJwPJEB8DyQwaYRyBGFCFtIrBHICDIR8izACEBcEFwgXDBcAFxQXGBccFxAXJBcoFywXIBc0FzgXPBcwF0QXSBdMF0AXVBdYF1wXUBdkF2gXbBdgF3QXeBd8F3HSEAIgZG2EcwRjAhAyLYRzBGMiH/IthHMEYxIW/wf0LYRzBGDCEKIthHIEYxRgAiuEdJ8hdKwPJJCiBG0EcAKFjQBkYgIMhH2LMHRgAgOHB4cLhw+HA4cXhxuHH4cThyeHK4cvhyOHN4c7hz+HM4dHh0uHT4dDh1eHW4dfh1OHZ4drh2+HY4d3h3uHf4d0Ty3GDC8gcAAmgSsThGWiHYRzhGWCFv8H9C2Ec4Rlkh/yLYR0v2GxMwRjlGACLA8kQDmEdBII34BABOII34BQAyII34BgAAII34BwAK8RgCAakwRpBHT/KbAzBGRiEWIsDyQwOYR2AgLGDIRwVGAChP8AMAH9AI9eNiKEYDJpBHLGBA8j8AwPIAAHhEQPLPY2hgwPJFAyhGFCFP9LJymEdA8txQQPIJQShjwPJFAShGbmSIR7IgA7C96PCPASADsL3o8I8CIAOwvejwj3BH",
    framedBytes: 522,
    badge: "AN2",
    tint: theme.tint.blue,
    title: "Bisect 2 — animation runs, callback does nothing",
    subtitle: "Starts the real animation with a no-op callback. Box labelled AN2 should sit still and survive.",
    tag: "no flash",
    trace: "FUT-234",
    divider: true,
    pushKey: "push_an2",
    pushLabel: "AN2",
  },
  {
    id: "anim",
    legacyConst: "PAYLOAD_ANIM_B64",
    source: "payload_anim.c",
    defines: [],
    b64:
      "RlhQMS3p8E+DsE/2v0gFRsDyRAgAIMBHACgA8PCATfaDYcDyQwGIRwAoAPDsgE/ywUNC9mkLRPbTSUv2GxdP8psGwPJDA8ghRiIERsDySAvA8kcJwPJEB8DyQwaYRyBGFCFtIrBHICDIR8izACEBcEFwgXDBcAFxQXGBccFxAXJBcoFywXIBc0FzgXPBcwF0QXSBdMF0AXVBdYF1wXUBdkF2gXbBdgF3QXeBd8F3HSEAIgZG2EcwRjAhAyLYRzBGMiH/IthHMEYxIW/wf0LYRzBGDCEKIthHIEYxRgAiuEdJ8hdKwPJJCiBG0EcAKFvQBkYgIMhH2LMHRgAgOHB4cLhw+HA4cXhxuHH4cThyeHK4cvhyOHN4c7hz+HM4dHh0uHT4dDh1eHW4dfh1OHZ4drh2+HY4d3h3uHf4d0Ty3GDC8gcAAmgSsThGWiHYRzhGWCFv8H9C2Ec4Rlkh/yLYR0v2GxMwRjlGACLA8kQDmEdBII34BABOII34BQBJII34BgBNII34BwAAII34CAAK8RgCAakwRpBHT/KbAzBGRiEWIsDyQwOYR2AgLGDIRwVGAChP8AMAH9AI9eNiKEYDJpBHLGBA8kEAwPIAAHhEQPLPY2hgwPJFAyhGFCFP9LJymEdA8txQQPIJQShjwPJFAShGbmSIRxogA7C96PCPASADsL3o8I8CIAOwvejwjwC/T/KbA8DyQwNtIhhH",
    framedBytes: 540,
    badge: "AN",
    tint: theme.danger,
    title: "Push animation — KNOWN CRASH, don't tap",
    subtitle: "The original FUT-234 payload. Crashed both lenses. Kept only for a controlled re-test.",
    tag: "CRASHES",
    tagTint: theme.danger,
    trace: "FUT-234",
    divider: true,
    pushKey: "push_anim",
    pushLabel: "animation",
  },
];

/** Look a payload up by manifest id. Throws rather than pushing `undefined`. */
export function payloadById(id: string): GeneratedPayload {
  const p = GENERATED_PAYLOADS.find((x) => x.id === id);
  if (!p) throw new Error(`no generated payload with id "${id}"`);
  return p;
}
