package expo.modules.ffsble.voice

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.security.MessageDigest

/**
 * The framer and the pipeline, run against REAL LC3 fixtures.
 *
 * WHY THESE MATTER MORE THAN THE REST OF THE SUITE
 * ------------------------------------------------
 * Everywhere else in these tests the "LC3 payload" is a byte pattern this repository invented,
 * which proves the framing rules but proves nothing about the bytes an encoder actually emits.
 * `src/test/resources/voice/fixture-*.g2a` are produced by `tools/lc3fixture/mkfixture.c` -- a
 * real LC3 encoder over a deterministic, speech-SHAPED but non-speech signal -- and they come
 * with a manifest stating, per packet, the exact `counter`, `ssr` and `tdoa` that were written.
 * That manifest is an ORACLE: it lets this file assert that our signed little-endian extraction
 * agrees with an independent implementation, including on the negative `ssr` values a hand-made
 * fixture would never have thought to include.
 *
 * ⛔ The fixtures contain NO human voice -- see `src/test/resources/voice/README.md`. `ffs_os` is
 * PUBLIC and no recording of the wearer, however short, ever becomes a test resource.
 *
 * These tests SKIP rather than fail when the resources are absent: they are generated by a
 * sibling stream, and a red suite because a peer has not landed yet teaches nobody anything.
 *
 * Run: ./gradlew :ffs-ble:testDebugUnitTest --tests 'expo.modules.ffsble.voice.*'
 */
class VoiceFramerTestFixtures {

    /** One row of the manifest's `packets` array. */
    private data class Row(val index: Int, val counter: Int, val ssr: Int, val tdoa: Int, val present: Boolean)

    private class Manifest(val json: String) {
        val rows: List<Row> = Regex(
            "\\{\\s*\"index\"\\s*:\\s*(-?\\d+)\\s*,\\s*\"counter\"\\s*:\\s*(-?\\d+)\\s*," +
                "\\s*\"ssr\"\\s*:\\s*(-?\\d+)\\s*,\\s*\"tdoa\"\\s*:\\s*(-?\\d+)\\s*," +
                "\\s*\"present\"\\s*:\\s*(true|false)"
        ).findAll(json).map {
            val g = it.groupValues
            Row(g[1].toInt(), g[2].toInt(), g[3].toInt(), g[4].toInt(), g[5] == "true")
        }.toList()

        fun num(key: String): Long? =
            Regex("\"" + Regex.escape(key) + "\"\\s*:\\s*(-?\\d+)").find(json)?.groupValues?.get(1)?.toLong()

        fun str(key: String): String? =
            Regex("\"" + Regex.escape(key) + "\"\\s*:\\s*\"([^\"]*)\"").find(json)?.groupValues?.get(1)

        /** `dropped_indices` as a set. An empty array yields an empty set. */
        fun droppedIndices(): Set<Int> {
            val body = Regex("\"dropped_indices\"\\s*:\\s*\\[([^\\]]*)\\]").find(json)
                ?.groupValues?.get(1)?.trim() ?: return emptySet()
            if (body.isEmpty()) return emptySet()
            return body.split(",").map { it.trim().toInt() }.toSet()
        }
    }

    private fun bytes(name: String): ByteArray? =
        javaClass.getResourceAsStream("/voice/$name")?.use { it.readBytes() }

    private fun manifest(name: String): Manifest? =
        javaClass.getResourceAsStream("/voice/$name")?.use { Manifest(String(it.readBytes(), Charsets.UTF_8)) }

    private fun sha256(b: ByteArray): String =
        MessageDigest.getInstance("SHA-256").digest(b).joinToString("") { "%02x".format(it) }

    /** Run the framer over a whole fixture, returning its stats and every action it took. */
    private fun frame(raw: ByteArray): Pair<VoiceFramerStats, List<FramerAction>> {
        val f = VoiceFramer()
        val actions = ArrayList<FramerAction>()
        var off = 0
        var t = 0L
        while (off + VoiceFormat.PACKET_BYTES <= raw.size) {
            val p = f.parse(raw, off, VoiceFormat.PACKET_BYTES, "R", t)
            if (p != null) actions.add(f.offer(p))
            off += VoiceFormat.PACKET_BYTES
            t += VoiceFormat.PACKET_MS
        }
        return f.stats() to actions
    }

    private fun decodeAll(raw: ByteArray, capacity: Int = 4096): Pair<List<VoiceAudioChunk>, VoicePipeline> {
        val chunks = ArrayList<VoiceAudioChunk>()
        val sink = object : VoiceSink {
            override fun onChunk(chunk: VoiceAudioChunk) { chunks.add(chunk) }
            override fun onStats(stats: VoiceFramerStats) {}
        }
        val p = VoicePipeline({ FakeLc3Decoder() }, sink, capacity)
        p.start()
        var off = 0
        while (off + VoiceFormat.PACKET_BYTES <= raw.size) {
            p.submit(raw.copyOfRange(off, off + VoiceFormat.PACKET_BYTES), "R")
            off += VoiceFormat.PACKET_BYTES
        }
        p.stop()
        return chunks to p
    }

    // -- the clean fixture -------------------------------------------------------------------

    @Test
    fun `the speech fixture is exactly the bytes its manifest pins`() {
        val raw = bytes("fixture-speech.g2a")
        val m = manifest("fixture-speech.json")
        assumeTrue("fixture-speech.{g2a,json} not present yet", raw != null && m != null)

        assertEquals(0, raw!!.size % VoiceFormat.PACKET_BYTES)
        m!!.num("g2a_bytes")?.let { assertEquals(it, raw.size.toLong()) }
        m.num("packets_written")?.let {
            assertEquals(it, (raw.size / VoiceFormat.PACKET_BYTES).toLong())
        }
        // The generator is deterministic and the manifest pins its output. A mismatch means the
        // fixture was regenerated with different parameters, and every number below is suspect.
        m.str("g2a_sha256")?.let { assertEquals("fixture sha256", it, sha256(raw)) }
        assertEquals(VoiceFormat.PACKET_BYTES.toLong(), m.num("packet_bytes"))
        assertEquals(VoiceFormat.SAMPLE_RATE.toLong(), m.num("sample_rate"))
        assertEquals(VoiceFormat.FRAME_US.toLong(), m.num("frame_us"))
        assertEquals(VoiceFormat.FRAME_BYTES.toLong(), m.num("frame_bytes"))
        assertEquals(VoiceFormat.FRAMES_PER_PACKET.toLong(), m.num("frames_per_packet"))
    }

    @Test
    fun `every counter, ssr and tdoa matches the manifest -- including the negative ones`() {
        val raw = bytes("fixture-speech.g2a")
        val m = manifest("fixture-speech.json")
        assumeTrue("fixture-speech.{g2a,json} not present yet", raw != null && m != null)

        val expected = m!!.rows.filter { it.present }
        assumeTrue("manifest has no packet rows", expected.isNotEmpty())
        assertEquals(expected.size, raw!!.size / VoiceFormat.PACKET_BYTES)

        // The whole point: an INDEPENDENT implementation wrote these int16s, and several of the
        // ssr values are negative (-3000, -156, ...). An unsigned read passes every synthetic
        // test in this suite and fails right here.
        val f = VoiceFramer()
        var sawNegative = false
        for ((i, row) in expected.withIndex()) {
            val p = f.parse(raw, i * VoiceFormat.PACKET_BYTES, VoiceFormat.PACKET_BYTES, "R", 0L)!!
            assertEquals("packet $i counter", row.counter and 0xFF, p.counter)
            assertEquals("packet $i ssr", row.ssr, p.ssr)
            assertEquals("packet $i tdoa", row.tdoa, p.tdoa)
            if (row.ssr < 0 || row.tdoa < 0) sawNegative = true
        }
        assertTrue("the fixture must exercise the signed path", sawNegative)
        assertEquals(0, f.stats().malformed)
    }

    @Test
    fun `the clean fixture frames with no loss, no concealment and no resync`() {
        val raw = bytes("fixture-speech.g2a")
        assumeTrue("fixture-speech.g2a not present yet", raw != null)
        val (s, actions) = frame(raw!!)
        assertEquals(raw.size / VoiceFormat.PACKET_BYTES, s.received)
        assertEquals(0, s.malformed)
        assertEquals(0, s.duplicates)
        assertEquals(0, s.lostPackets)
        assertEquals(0, s.concealed)
        assertEquals(0, s.resyncs)
        assertTrue(actions.all { it == FramerAction.Deliver(0) })
    }

    @Test
    fun `the clean fixture decodes to one 800-sample chunk per packet`() {
        val raw = bytes("fixture-speech.g2a")
        val m = manifest("fixture-speech.json")
        assumeTrue("fixture-speech.{g2a,json} not present yet", raw != null && m != null)

        val (chunks, p) = decodeAll(raw!!)
        val n = raw.size / VoiceFormat.PACKET_BYTES
        assertEquals(n, chunks.size)
        assertEquals(0, p.overruns)
        assertEquals(0, p.stats().malformed)
        assertTrue(chunks.none { it.concealed })
        assertTrue(chunks.all { it.samples == VoiceFormat.SAMPLES_PER_PACKET })

        // The manifest states the duration; 800 samples per packet must reproduce it exactly.
        val samples = chunks.sumOf { it.samples }
        m!!.num("duration_ms")?.let {
            assertEquals("decoded duration", it, samples.toLong() * 1000L / VoiceFormat.SAMPLE_RATE)
        }

        // Metadata survives the whole journey, per packet, in order.
        val present = m.rows.filter { it.present }
        for (i in chunks.indices) {
            assertEquals("chunk $i ssr", present[i].ssr, chunks[i].ssr)
            assertEquals("chunk $i tdoa", present[i].tdoa, chunks[i].tdoa)
        }
    }

    // -- the gaps fixture --------------------------------------------------------------------

    @Test
    fun `the gaps fixture recovers its exact loss count from the counter alone`() {
        val raw = bytes("fixture-gaps.g2a")
        val m = manifest("fixture-gaps.json")
        assumeTrue("fixture-gaps.{g2a,json} not present yet", raw != null && m != null)

        m!!.str("g2a_sha256")?.let { assertEquals("fixture sha256", it, sha256(raw!!)) }
        val dropped = m.droppedIndices()
        assumeTrue("the gaps manifest lists no drops", dropped.isNotEmpty())

        val (s, _) = frame(raw!!)
        assertEquals(raw.size / VoiceFormat.PACKET_BYTES, s.received)
        assertEquals(0, s.malformed)
        // THE assertion of this file: the generator withheld N packets, and byte 204 -- the only
        // loss signal this pipe has -- must let us arrive at the same N without being told.
        assertEquals("framer must recover the manifest's loss count", dropped.size, s.lostPackets)
    }

    @Test
    fun `small holes are concealed and the ten-packet hole resyncs`() {
        val raw = bytes("fixture-gaps.g2a")
        val m = manifest("fixture-gaps.json")
        assumeTrue("fixture-gaps.{g2a,json} not present yet", raw != null && m != null)

        val dropped = m!!.droppedIndices()
        assumeTrue("the gaps manifest lists no drops", dropped.isNotEmpty())

        // Work out, from the manifest alone, which runs of consecutive drops there are and how
        // each SHOULD be handled -- so this test keeps meaning something if the fixture changes.
        val runs = ArrayList<Int>()
        var run = 0
        for (i in 0..(m.rows.maxOf { it.index })) {
            if (i in dropped) run++ else if (run > 0) { runs.add(run); run = 0 }
        }
        if (run > 0) runs.add(run)

        val concealable = runs.filter { it + 1 <= VoiceFramer.MAX_CONCEAL_GAP }
        val resyncing = runs.filter { it + 1 > VoiceFramer.MAX_CONCEAL_GAP }

        val (s, actions) = frame(raw!!)
        assertEquals(
            "every small hole becomes five PLC frames per lost packet",
            concealable.sum() * VoiceFormat.FRAMES_PER_PACKET,
            s.concealed
        )
        assertEquals("every oversized hole becomes a resync", resyncing.size, s.resyncs)
        assertEquals(resyncing.size, actions.count { it is FramerAction.Resync })
        assertEquals(
            concealable.size,
            actions.count { it is FramerAction.Deliver && it.concealBefore > 0 }
        )
    }

    @Test
    fun `the gaps fixture decodes with PLC in the holes and nothing fabricated across the resync`() {
        val raw = bytes("fixture-gaps.g2a")
        val m = manifest("fixture-gaps.json")
        assumeTrue("fixture-gaps.{g2a,json} not present yet", raw != null && m != null)

        val (s, _) = frame(raw!!)
        val (chunks, p) = decodeAll(raw)

        val real = raw.size / VoiceFormat.PACKET_BYTES
        val concealChunks = s.concealed / VoiceFormat.FRAMES_PER_PACKET
        assertEquals(real + concealChunks, chunks.size)
        assertEquals(concealChunks, chunks.count { it.concealed })
        assertEquals(0, p.overruns)

        // ⚠️ CONTRACT NOTE, deliberate: the fixture README suggests a decoder should emit the
        // FULL 32000 samples, concealing the ten-packet hole too. This pipeline does NOT: past
        // VoiceFramer.MAX_CONCEAL_GAP we resync and leave the hole, because half a second of
        // synthesised filler is indistinguishable from speech to an STT provider and would put
        // words in the wearer's mouth that were never said. The hole is COUNTED instead
        // (resyncs / lostPackets), which is the honest form of the same information.
        val lostAcrossResync = s.lostPackets - concealChunks
        assertTrue("the oversized hole must not be concealed", lostAcrossResync > 0)
        assertEquals(
            "timeline accounting must add up",
            real + s.lostPackets,
            chunks.size + lostAcrossResync
        )

        // Every concealed chunk really is PLC output, all five frames of it.
        for (c in chunks.filter { it.concealed }) {
            for (f in 0 until VoiceFormat.FRAMES_PER_PACKET) {
                assertTrue(FakeLc3Decoder.isConcealFrame(c.pcm, f * VoiceFormat.SAMPLES_PER_FRAME))
            }
        }
    }

    @Test
    fun `a fixture archives and re-derives to the same audio`() {
        val raw = bytes("fixture-speech.g2a")
        assumeTrue("fixture-speech.g2a not present yet", raw != null)

        val root = java.nio.file.Files.createTempDirectory("ffs-voice-fixture").toFile()
        try {
            val archive = VoiceArchiveFiles(root)
            val n = raw!!.size / VoiceFormat.PACKET_BYTES
            archive.open("fixture", 1_700_000_000_000L).use { w ->
                var off = 0
                while (off + VoiceFormat.PACKET_BYTES <= raw.size) {
                    w.append(raw.copyOfRange(off, off + VoiceFormat.PACKET_BYTES))
                    off += VoiceFormat.PACKET_BYTES
                }
            }
            // The master is the wire bytes, unchanged -- that is what "lossless master" means.
            assertEquals(raw.size.toLong(), archive.masterFile("fixture").length())
            assertEquals(sha256(raw), sha256(archive.masterFile("fixture").readBytes()))

            val wav = java.io.File(root, "fixture.wav")
            val result = archive.deriveWav(archive.masterFile("fixture"), wav, FakeLc3Decoder())
            assertEquals(n.toLong(), result.packetsRead)
            assertEquals(n.toLong(), result.chunksWritten)
            assertEquals(
                (WavWriter.HEADER_BYTES + n * VoiceFormat.SAMPLES_PER_PACKET * 2).toLong(),
                wav.length()
            )
        } finally {
            root.deleteRecursively()
        }
    }
}
