// BYTE-GOLDEN ORACLE — validate our wire against an INDEPENDENT implementation.
//
// The golden vectors below are the output of `gpsnmeajp/men-g2-ble-gateway` (MIT), a clean Python
// port of MentraOS's `G2.kt` split into `crc.py` (CRC-16) + `transport.py` (`build_packets`). They
// were generated by RUNNING that project's `calc_crc16` and its exact `build_packets` framing rule
// over representative payloads, then frozen here as hex. Nothing in this file is generated by our
// own code — that is the whole point: our `crc16CcittFalse` and `frameMessage` have to reproduce
// bytes an outside project produced, or one of us is wrong.
//
// Provenance / attribution (all MIT, cross-check only — no code vendored):
//   • men-g2-ble-gateway  `mentraos/g2/crc.py`, `mentraos/g2/transport.py`  (the oracle here)
//   • MentraOS/MentraOS   `sgcs/G2.kt`                                       (the port's source)
//
// FINDING (see the report): our bytes MATCH the oracle exactly on every vector, including the
// CCITT-FALSE check value 0x29B1 for "123456789". The gateway/Kotlin CRC is written as a
// byte-swap/xor "bit-mix" and OURS as a textbook MSB-first table walk; the check value proves they
// are the SAME function, so the readable form we keep in `crc.ts` inherits the oracle's evidence.

import { crc16CcittFalse } from "../crc";
import { Flag, frameMessage, parseFrame } from "../envelope";

/** hex string -> bytes. */
const hb = (h: string): number[] => {
  const out: number[] = [];
  for (let i = 0; i < h.length; i += 2) out.push(parseInt(h.slice(i, i + 2), 16));
  return out;
};
/** bytes -> lowercase hex, the shape the oracle emits. */
const hex = (b: Uint8Array): string =>
  Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");

/** reserveFlag true -> status 0x20 (our Flag.REQUEST); false -> 0x00 (Flag.RESPONSE). */
const flagFor = (reserve: boolean) => (reserve ? Flag.REQUEST : Flag.RESPONSE);

describe("oracle — CRC-16 matches men-g2-ble-gateway calc_crc16", () => {
  // Values straight out of the gateway's crc.py, computed by running it (see report).
  it("CCITT-FALSE check value", () => {
    expect(crc16CcittFalse(new TextEncoder().encode("123456789"))).toBe(0x29b1);
  });
  it("empty input is the 0xFFFF seed", () => {
    expect(crc16CcittFalse(new Uint8Array(0))).toBe(0xffff);
  });
  it('"hello" — the gateway and Kotlin G2ProtocolTest both say 0xD26E', () => {
    expect(crc16CcittFalse(new TextEncoder().encode("hello"))).toBe(0xd26e);
  });
});

// Each case: the gateway's build_packets(sync, sid, payload, reserve) output, as hex packets.
interface Vec {
  name: string;
  sync: number;
  sid: number;
  reserve: boolean;
  payload: number[];
  packets: string[];
}

const seq = (n: number): number[] => Array.from({ length: n }, (_, i) => i & 0xff);

const VECTORS: Vec[] = [
  {
    name: "empty payload on sid 0x09 — one CRC-only packet",
    sync: 0,
    sid: 0x09,
    reserve: false,
    payload: [],
    packets: ["aa21000201010900ffff"],
  },
  {
    name: "short EvenHub payload, reserveFlag set (status 0x20)",
    sync: 5,
    sid: 0xe0,
    reserve: true,
    payload: hb("08001001"),
    packets: ["aa2105060101e020080010015112"],
  },
  {
    name: "exactly 236-byte chunk — extra empty CRC packet appended",
    sync: 7,
    sid: 0xe0,
    reserve: true,
    payload: seq(236),
    packets: [
      "aa2107ec0201e020" + hex(Uint8Array.from(seq(236))),
      "aa2107020202e0206a71",
    ],
  },
  {
    name: "300-byte payload — two fragments, CRC on the last",
    sync: 9,
    sid: 0xe0,
    reserve: true,
    payload: seq(300),
    packets: [
      "aa2109ec0201e020" + hex(Uint8Array.from(seq(236))),
      "aa2109420202e020" + hex(Uint8Array.from(seq(300).slice(236))) + "59a9",
    ],
  },
  {
    name: "a settings-shaped payload on sid 0x09",
    sync: 3,
    sid: 0x09,
    reserve: false,
    payload: hb("0801104d1a0622040800100f"),
    packets: ["aa21030e010109000801104d1a0622040800100f989f"],
  },
];

describe("oracle — frameMessage matches men-g2-ble-gateway build_packets", () => {
  for (const v of VECTORS) {
    it(v.name, () => {
      const frames = frameMessage(Uint8Array.from(v.payload), {
        syncId: v.sync,
        sid: v.sid,
        flag: flagFor(v.reserve),
      });
      expect(frames.map((f) => hex(f))).toEqual(v.packets);
    });
  }

  it("our parseFrame round-trips the oracle's own bytes (header fields agree)", () => {
    // Take the oracle's last multi-fragment packet and confirm we read its header the way the
    // gateway wrote it — a second, structural cross-check that isn't just byte-equality.
    const last = Uint8Array.from(hb(VECTORS[3]!.packets[1]!));
    const p = parseFrame(last);
    expect(p.ok).toBe(true);
    expect(p.isTx).toBe(true);
    expect(p.syncId).toBe(9);
    expect(p.totalPackets).toBe(2);
    expect(p.serial).toBe(2);
    expect(p.sid).toBe(0xe0);
    expect(p.flag).toBe(0x20);
  });
});
