#!/usr/bin/env python3
"""
Embed the prebuilt CFW payload-interpreter blobs into the app as base64 constants.

WHY THIS EXISTS
---------------
`payloads/ffs_screen.c` and `payloads/ffs_dashboard.c` in the g2flash CFW repo are
INTERPRETERS: each carries a fixed-size descriptor in .rodata, and renders whatever it
finds there. So a new screen (or a new dashboard configuration) is DATA, not code — the
phone rewrites those bytes in a prebuilt template, recomputes the FXP1 CRC, and pushes.

Until now the rewriting half lived only in `g2flash/tools/patch_dash.py` and
`patch_screen.py`, which means every configuration had to be produced on a dev machine
and injected with

    adb shell am broadcast -a com.futurefounders.ffs.PUSH_PAYLOAD --es b64 <base64>

i.e. the app could not change its own dashboard. Bundling the templates moves that
capability into the APK: `src/sdk/templates.ts` does the patching at runtime and the
existing `pushPayloadViaImage` path ships the result.

WHY BASE64-IN-TYPESCRIPT AND NOT AN ANDROID ASSET
------------------------------------------------
`android/` is gitignored in this repo and regenerated by `npx expo prebuild` (see
.gitignore, "generated native folders"), so anything dropped in
android/app/src/main/assets/ is neither committed nor survives a prebuild --clean. The
JS bundle IS the app's asset store here, and the repo already carries ~50 payloads that
way in `src/os/payloads.generated.ts`. This follows that idiom.

The blobs are OUR code (payloads/*.c, MIT-ish internal), NOT Even's firmware — nothing
here is derived from a firmware image, so it is safe in a public repo.

USAGE
    python3 scripts/embed-templates.py                    # ../g2flash next to this repo
    python3 scripts/embed-templates.py --g2flash ~/src/g2flash
    python3 scripts/embed-templates.py --check            # fail if the file is stale

Rebuild the blobs first:
    python3 patches/build.py payloads/ffs_screen.c
    python3 patches/build.py payloads/ffs_dashboard.c
"""
from __future__ import annotations

import argparse
import base64
import struct
import sys
import zlib
from pathlib import Path

# This script prints non-ASCII status glyphs and Windows consoles default to cp1252, so
# those raise UnicodeEncodeError and the check "fails" having actually passed. Same fix as
# scripts/check-reachable.py, for the same reason: Windows is the dev box.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "src" / "sdk" / "templates.generated.ts"

# name -> (blob under g2flash/obj, descriptor magic, descriptor size in bytes)
# The sizes must match patches/ffs_screen.h and payloads/ffs_dashboard.c exactly; they are
# asserted against the blob below, because a short read here would corrupt code, not data.
TEMPLATES = {
    "screen": ("obj/ffs_screen.text.bin", 0x44534646, 12 + 232 * 6),  # "FFSD"
    "dashboard": ("obj/ffs_dashboard.text.bin", 0x42445346, 32),      # "FSDB"
}

HEADER = '''// AUTO-GENERATED by scripts/embed-templates.py — DO NOT EDIT BY HAND.
//
//   regenerate:  python3 scripts/embed-templates.py --g2flash <path to g2flash>
//   source of truth:  g2flash/payloads/ffs_screen.c + ffs_dashboard.c, built by
//                     g2flash/patches/build.py into g2flash/obj/<name>.text.bin
//
// These are the PAYLOAD INTERPRETERS: each blob carries a fixed-size descriptor in its
// .rodata, and draws whatever that descriptor says. The phone overwrites the descriptor
// and pushes — no rebuild, no reflash, one template forever. See src/sdk/templates.ts
// for the patcher and g2flash/docs/SDK-PARAMETERISATION.md for why it is done this way.
//
// ⚠️ `b64` here is the RAW blob — NOT FXP1-framed, unlike payloads.generated.ts. It cannot
// be pushed as-is: the descriptor has to be written first and the frame CRC computed over
// the RESULT. `templates.ts` does both. Pushing an unframed blob fails silently — the
// firmware's image dispatch switches on the first byte, a Thumb blob starts with 0x2D,
// that matches no image mode, and it is dropped before the loader ever sees it.

export type PayloadTemplate = {
  /** payloads/<id>.c in the g2flash CFW repo */
  id: string;
  /** base64 of the RAW blob (no FXP1 frame) */
  b64: string;
  /** length of the raw blob in bytes */
  bytes: number;
  /** zlib crc32 of the UNPATCHED blob — a build-provenance fingerprint, not a runtime check */
  crc32: number;
  /** little-endian u32 that marks the descriptor inside the blob */
  magic: number;
  /** byte offset of the descriptor in THIS build (the patcher re-finds it by magic anyway) */
  descOffset: number;
  /** descriptor size — the exact number of bytes the patcher may overwrite */
  descBytes: number;
};

'''


def emit(g2flash: Path) -> str:
    out = [HEADER]
    for name, (rel, magic, desc_bytes) in TEMPLATES.items():
        path = g2flash / rel
        if not path.is_file():
            sys.exit(f"missing {path} — build it: python3 patches/build.py payloads/{path.stem.replace('.text', '')}.c")
        blob = path.read_bytes()

        needle = struct.pack("<I", magic)
        at = blob.find(needle)
        if at < 0:
            sys.exit(
                f"{path}: descriptor magic 0x{magic:08X} not found. The optimiser folds an\n"
                "all-scalar descriptor into the code unless the asm barrier is present —\n"
                "rebuild and check the blob grew a .rodata section."
            )
        if blob.find(needle, at + 1) >= 0:
            sys.exit(f"{path}: more than one 0x{magic:08X} in the blob; refusing to guess which is the descriptor")
        if at + desc_bytes > len(blob):
            sys.exit(f"{path}: descriptor at {at} + {desc_bytes} B runs past the {len(blob)} B blob — header drift?")

        ident = name.upper()
        out.append(
            f"export const TEMPLATE_{ident}: PayloadTemplate = {{\n"
            f'  id: "ffs_{name}",\n'
            f"  b64:\n"
            f'    "{base64.b64encode(blob).decode()}",\n'
            f"  bytes: {len(blob)},\n"
            f"  crc32: 0x{zlib.crc32(blob) & 0xFFFFFFFF:08x},\n"
            f"  magic: 0x{magic:08x},\n"
            f"  descOffset: {at},\n"
            f"  descBytes: {desc_bytes},\n"
            f"}};\n\n"
        )
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--g2flash", type=Path, default=REPO.parent / "g2flash",
                    help="path to the g2flash checkout (default: ../g2flash)")
    ap.add_argument("--check", action="store_true", help="exit non-zero if the generated file is stale")
    args = ap.parse_args()

    text = emit(args.g2flash.resolve())

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text:
            print(f"✖ {OUT.relative_to(REPO)} is STALE — rerun scripts/embed-templates.py", file=sys.stderr)
            return 1
        print(f"✔ {OUT.relative_to(REPO).as_posix()} matches the built blobs")
        return 0

    # LF, always: .gitattributes pins it for build reproducibility.
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(REPO).as_posix()} ({len(text)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
